spring:
  kafka:
    producer:
      bootstrap-servers: kafka.ambari.com:9095
      acks: all
      retries: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

